version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: async
    versions:
    - ">= 3.a, < 4"
  - dependency-name: pandoc-filter
    versions:
    - ">= 2.a, < 3"
